### PR TITLE
MODE-2599 Added Travis-CI build

### PR DESCRIPTION
**Pull request by rhauch**
The build just runs `mvn -s settings.xml clean install -Pintegration`

### CODE REVIEW

**Comment by hchiorean** [comment]
+1 (except that build job seems to be failing)

**Comment by hchiorean** [comment]
@rhauch: the missing artifacts should (hopefully) be resolvable by updating `settings.xml` and adding & enabling the following repo:
```
<profile>
            <id>jboss-thirdpartyuploads-repository</id>
            <repositories>
                <repository>
                    <!--This repository is required for the Fungal artifact used by ModeShape JCA -->
                    <id>jboss-thirdpartyuploads-repository</id>
                    <name>JBoss Third Party Uploads Repository</name>
                    <url>http://repository.jboss.org/nexus/content/repositories/thirdparty-uploads/</url>
                    <layout>default</layout>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                        <updatePolicy>never</updatePolicy>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
```

which is required for the JCA stuff anyway

**Comment by rhauch** [comment]
@hchiorean, yes, the problem is that Travis is running a pre-build `mvn` command to install dependencies, and I forgot to override that. Trying again.

**Comment by rhauch** [comment]
The latest problem appears to be that the Git connector tests are assuming the existence of a local git repo that has tags, but the Travis build does not include tags when it clones the repo prior to the build using:

    git clone --depth=50 https://github.com/ModeShape/modeshape.git ModeShape/modeshape

IMO, if the tests need a local copy of the Git repo, then they should clone the Git repo into a target directory for use by the tests.

**Comment by hchiorean** [comment]
Merged in `master`, although the current failure is 
`The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).` and is due to Maven logging a lot of output 

There are several Travis issues on this topic, including an open feature request to allow making this limit configurable, but there is no clear solution yet.

**Pull request merged**
