### PR TITLE
MODE-2635 Adds replica-set support for the Mongo binary store to the JSON and WF configs

### PR DESCRIPTION
**Pull request by hchiorean**

### CODE REVIEW

**Comment by hchiorean** [comment]
@rhauch are you with merging this ?

**Comment by rhauch** [comment]
@hchiorean Rather than use `replica-sets` as the configuration properties, I think we should use `host-addresses` so that we can reuse it for sharded clusters if we ever need to. We still need to keep the `host` and `port` config properties for backward compatibility.

Then, I would suggest changing the MongodbBinaryStore class to use `List<ServerAddress>` in place of the `host`, `port`, and `replicaSets` fields. The ServerAddress given by the `host` and `port` should just be placed first in the `List<ServerAddress>`, as long as that list contains unique values. This way we can handle all of the configuration properties in the most meaningful and natural way.

**Comment by hchiorean** [comment]
amended the commit

**Comment by rhauch** [comment]
It'd be great if 'host' and 'port' were made optional in the configuration, but I understand why that might be an issue. Looks good.

**Comment by hchiorean** [comment]
I could make them optional both in the JSON schema and WF schema if you feel that's important. That would require some custom validation though to make sure either `host` and `port` or `hostAddresses` are present

**Comment by rhauch** [comment]
Would be nice if we could use only `host-addresses` in newer or updated deployments, but making sure either exists is the hard part. I'll leave it up to you to decide whether the custom validation is worth it.

**Comment by hchiorean** [comment]
I've added another commit which makes `host` and `port` optional from a configuration perspective and performs the validation in the `MongoDBBinaryStore` constructor so that either `host:port` or `hostAddresses` are provided

**Comment by rhauch** [comment]
@hchiorean awesome! Looks great.

**Pull request merged**
