### PR TITLE
MODE-2552 Adds sequencer for several audio formats

### PR DESCRIPTION
**Pull request by RobSis**
New pull request against the master branch. 

First review was done here:
https://github.com/ModeShape/modeshape/pull/1502

### CODE REVIEW

**Comment by hchiorean** [comment]
looks good
@rhauch  ?

**Comment by rhauch** [comment]
Looks good to me.

**Comment by hchiorean** [comment]
@RobSis: this no longer merges cleanly after merging https://github.com/ModeShape/modeshape/pull/1554
Please fix it in your local branch and force update (`push -f`) this PR. Thanks.

**Comment by hchiorean** [comment]
@rhauch: bringing this in, will present a bit of a conundrum: we already have an `mp3` sequencer which uses the same library and does some (modest) mp3 parsing. 

This sequencer supports multiple audio formats (mp3 included) but with a different (more detailed and generic) structure.

So IMO we have a couple of options:
1.add this and keep both sequencers side-by-side while deprecating the `mp3` sequencer (marking its classes as deprecated)
2.merge the 2 sequencers into one (named `audio` which is more generic)

(1) means no changes are required as this one will be a new addition
(2) means if anyone (*if*) is using the mp3 sequencer they'd have to change their configuration

wdyt ?

**Comment by RobSis** [comment]
Note that I'm adding this to binary distributions again. 

I've noticed you removed video sequencer from it, so I'm not sure whether this sequencer should be there...

**Comment by hchiorean** [comment]
this should be part of the binary dist (as is the case with the other sequencers as well).

The problem I have with the video sequencer (as described [here](https://issues.jboss.org/browse/MODE-2553?focusedCommentId=13238390&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13238390)) is that the size of its `io.humble` dependency is about `115 MB`. This is *way way* too big for a sequencer for us to bundle and deliver.

**Comment by hchiorean** [comment]
@rhauch any thoughts on https://github.com/ModeShape/modeshape/pull/1555#issuecomment-219670791 ?

**Comment by hchiorean** [comment]
@RobSis: with the merging of the other sequencers, this again needs to be brought up to date with `master`.

**Pull request merged**
