### PR TITLE
Support using profile-based credentials for S3 binary storage

### PR DESCRIPTION
**Pull request by dalbani**
https://issues.jboss.org/browse/MODE-2693

### CODE REVIEW

**Comment by hchiorean** [comment]
this looks good, but requires at least 1 unit test to validate the enhancement (see https://github.com/ModeShape/modeshape/blob/master/modeshape-jcr/src/test/java/org/modeshape/jcr/value/binary/S3BinaryStoreTest.java)

**Comment by dalbani** [comment]
@hchiorean  
I will a new entry in `modeshape-s3-binary-storage.xml` then.
But I don't really see how I'm supposed to alter `S3BinaryStoreTest.java` to test the profile credentials feature. Any idea?

**Comment by hchiorean** [comment]
@dalbani I didn't see that that `S3BinaryStoreTest` mocks everything... in this case I doubt a test would really be useful. 

So just the test for the AS7 subsystem is ok.

**Comment by dalbani** [comment]
Test entry added.

**Comment by hchiorean** [comment]
please squash the 2 commits; everything else looks fine

**Comment by dalbani** [comment]
Squashed.

**Pull request merged**
