### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by weebl2000**

### CODE REVIEW

**Comment by hchiorean** [comment]
tx for the fix, but that text is flawed and we'll have to revisit it ;)

**Comment by weebl2000** [comment]
I agree that a distributed infinispan cache is NOT appropriate for Modeshape usage. We have tried it, but it leads to horrible inconsistencies.

**Comment by rhauch** [comment]
@hchiorean, go ahead and merge. We need to fix this file anyway like you did for the documentation.

**Comment by weebl2000** [comment]
Btw, use case where infinispan might work in distributed mode is where there is no shared cache store. Have not tried though.

**Pull request merged**
