### PR TITLE
MODE-2642 Removes the RepositoryFeaturesDetector optimization for #isCheckedOut and #isLocked

### PR DESCRIPTION
**Pull request by hchiorean**
This was introduced as part of https://issues.jboss.org/browse/MODE-2277 to optimize the read access of the `node#isCheckedOut` method, but the entire concept is flawed when user transactions are used. User transactions are isolated from the repository and do not trigger any notifications until the transaction is committed.

### CODE REVIEW

**Comment by hchiorean** [comment]
@rhauch  another `Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use (Internal Server Error: 500)` failure, even though ModeShape uses only 1 instance of a docker container which should be started/stopped once during the `persistence-tests`

I'm not sure wth is going on, the same build passes fine on my machine. Any ideas ?

**Comment by rhauch** [comment]
@hchiorean try using a different port. I think Travis-CI changed recently and now port 3306 is already bound even though we don't set up Travis' MySQL server.

**Comment by hchiorean** [comment]
@rhauch : the exact same error occurs with Postgres and port 5432. I'm not sure adding custom configuration files for all the docker images is desirable. Actually, it's not even possible for PG since the base docker image exposes 5432 explicitly.

**Comment by rhauch** [comment]
I'll file an issue with Travis-CI, and hopefully they will correct their environment. In the meantime, changing the port for the MySQL container should work.

**Comment by hchiorean** [comment]
@rhauch that did the trick, thanks

**Comment by hchiorean** [comment]
@rhauch are you ok with the changes ?

**Comment by rhauch** [comment]
@hchiorean looks good.

**Pull request merged**
