### PR TITLE
MODE-2550 Adds OpenDocument Format sequencer

### PR DESCRIPTION
**Pull request by RobSis**
New pull request against the master branch. 

First review was done here:
https://github.com/ModeShape/modeshape/pull/1500

### CODE REVIEW

**Comment by hchiorean** [comment]
@RobSis: again, please rebase it on the latest master and update it. tx

**Comment by hchiorean** [comment]
beside the above, this looks good.
@rhauch ?

**Comment by RobSis** [comment]
Thanks! This is the last one, btw ;)

**Comment by hchiorean** [comment]
@rhauch are you ok with merging this ?

**Comment by rhauch** [comment]
Looks good.

**Comment by hchiorean** [comment]
@RobSis: this cannot be merged because of the following build error:
```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.modeshape:modeshape-distribution:5.1-SNAPSHOT (D:\Work\upstream.modeshape\modeshape-distribution\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.modeshape:modeshape-sequencer-odf:jar is missing. @ line 143, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
```

Most likely this is because the new artifact `modeshape-sequencer-odf` is missing from `modeshape-parent`

**Comment by hchiorean** [comment]
@RobSis: can you please fix the above error and update the PR (`push -f`). thanks.

**Pull request merged**
