### PR TITLE
MODE-2439 Oracle DDL parser enhacement

### PR DESCRIPTION
**Pull request by freakolowsky**
Added support for multiple ADD/MODIFY clauses in ALTER TABLE
statements and some minor changes to MODE-2350

### CODE REVIEW

**Comment by freakolowsky** [comment]
PS: sry for dropping off the grid on my previous pull request

**Comment by hchiorean** [comment]
looks good

**Comment by freakolowsky** [comment]
i might have one more change to drop on this ... do i need a new pull request or is it possible to just update this one?

**Comment by hchiorean** [comment]
@freakolowsky: just add another commit on this one or amend it and force push altogether.

**Comment by freakolowsky** [comment]
ok, should be ok now ... let my actions be judged :D

**Comment by freakolowsky** [comment]
found a minor bug ... not related to this enhancement ...

**Comment by rhauch** [comment]
Looks good.

**Pull request merged**
