### PR TITLE
MODE-2591 Changes the name of the datasource JNDI attribute for the DB persistence

### PR DESCRIPTION
**Pull request by hchiorean**
This should now match the other DS JNDI names used by the database binary store and JDBC metadata connector.

### CODE REVIEW

**Comment by rhauch** [comment]
@hchiorean: Please confirm, but it appears that this will break any existing 5.0 configurations that use this. I understand the desire to correct this and eliminate potential problems for users (thus MODE-2591), but IMO any change like this needs to be backward compatible. IOW, it's okay to *add* the new property and even deprecate the old properties, but the subsystem still needs to be able to read and use the old properties.

**Comment by hchiorean** [comment]
@rhauch: the change is intentional; deprecating the old property requires a lot of leftover boilerplate code to the point where I'd really not make this change at all (this was my original approach). 
Not only that, but there is no easy of elegant way to deprecate attributes in XML. We'd essentially be supporting 2 different names, with minor variation, for the same attribute.

My plan was to change the name altogether and update the release notes and documentation (it's a rather small change after all).

If you're not ok with it, I'm fine with moving/targeting this to the next major ModeShape release as opposed to deprecating the attributes, for the reasons mentioned above.

**Comment by rhauch** [comment]
@hchiorean, it's up to you.

**Comment by hchiorean** [comment]
@rhauch so you're ok with either option ?

**Comment by rhauch** [comment]
@hchiorean, Sure. I just wanted to make sure the change was intentional.

**Pull request merged**
